name: Build docker images
on:
  push:
    branches:
      - 'master'
permissions:
  packages: write
  contents: read

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - name: GHCR-Action
        uses: KuhlTime/ghcr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
  arm64:
    runs-on: macos-latest
    steps:
      - name: GHCR-Action
        uses: KuhlTime/ghcr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            BUILDARCH: "arm64"
