name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the amd64 image
      run: docker build . --tag solana:amd64
    - name: Push the image
      run: docker push ghcr.io/devs-group/solana:amd64
      
  arm64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the arm64 image
      run: docker build . --build-arg BUILDARCH=arm64 --tag solana:arm64
